## Python review 

Goals: 
- recal basic python vocabulary 
- practice markdown 

## Libraries and packages

**Library** : a collection of code that we can use to perfomr specific tasks in our programs . 

**NumPy** : 
- core library for numerical computering in python 
- many other libraryes use NumPy arrays as building blocks 
- computations on NumPy are opitimed for speeds and memory usage 

Lets import NumPy with ** standard abbrvation** 

In [2]:
import numpy as np

## Variables 

**Variables** : A name we assign to a particular object in Pythonn 

Example: 

In [3]:
# Assign a small array to cariable a 
a = np.array([[1,1,2], [3,5,8]])

In [5]:
# Run cell with variable name to show value 
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
# Use 'print' function to print the value 
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**Object** (informally speaking) is a buncle of *properties* and *actions* about somethung specific. 

Examples: 

Object: data frame 

Properties: number rows, names of columns, date created

Actions: selecting a specific row, adding a new column 

A variable is the name we give a specific object, and the same object can be references by different variables. 

In practice, we can often use variable and object interchangeably.
