## Python review 

Goals: 
- recal basic python vocabulary 
- practice markdown 

## Libraries and packages

**Library** : a collection of code that we can use to perfomr specific tasks in our programs . 

**NumPy** : 
- core library for numerical computering in python 
- many other libraryes use NumPy arrays as building blocks 
- computations on NumPy are opitimed for speeds and memory usage 

Lets import NumPy with ** standard abbrvation** 

In [1]:
import numpy as np

## Variables 

**Variables** : A name we assign to a particular object in Pythonn 

Example: 

In [2]:
# Assign a small array to cariable a 
a = np.array([[1,1,2], [3,5,8]])

In [3]:
# Run cell with variable name to show value 
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use 'print' function to print the value 
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**Object** (informally speaking) is a buncle of *properties* and *actions* about something specific. 

Examples: 

Object: data frame 

Properties: number rows, names of columns, date created

Actions: selecting a specific row, adding a new column 

A variable is the name we give a specific object, and the same object can be references by different variables. 

In practice, we can often use variable and object interchangeably.

## Types

EVery object in Python as a **type** and the type tell us what kind of object it is. 

We can also call the type of an object, the **class** of an object and they both mean what kind of object we have. 



In [6]:
print(a)

# check the type/class of a variable/object by using the 'type' function 
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [8]:
print(a[0,0])

# check the type of an entry on the array by indexig 
type(a[0,0])

1


numpy.int64

Notice that 'type(a[0,0])' is 'numpy.int64' and not just the standard python integer type. This is telling us that 1 is an interger stored as a 64-bit number. 

In [9]:
a[1,1]

5

## Functions 

'print' was our first example of a python **function**. 

Functions take in a set of **arguments** and thise aruguments create a **output** 

argument = parameter 

WE can ask infomation about a function by excuting '?function'

In [10]:
# this informtion is a docstring 
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

**docstring**

A function has 2 tyoes of arugments: 
 - **non-optional arguments**: agruments you need to specify for the function to do something 
 - **opitional arguments**: arguments that are pre-filled with a default valye by the function. You can override them. Opitional arguments appear inside the parenthesis in the form `opitional_agument=default_value`

In [12]:
print('changing the default end argument', end=' :)')

changing the default end argument :)

## Attributes and methods

An object in Python ha sattributes and methods 

- **attributes**: a properity of an object, some piece of information about it 
    - varaible.attribute
- **methods**: functions / procedure assocaited with the object 
    - variable.method()

In [21]:
# Examples 

# Attributes 
print(a.shape)
print(type(a.shape))

(2, 3)
<class 'tuple'>


In [26]:
# Methods 
print(a.min(axis=0))   # min returns the minimum valies along a specified axis 
print(a.min(axis=1))

[1 1 2]
[1 3]


In [25]:
# Check in: call min without parameters 
a.min()

1

Remember: methods are functions assocaited with an object

In [27]:
type(a.min)

builtin_function_or_method

## Exercise
1. Read the `print` function help. What is the type of the arugment `sep`? Is this an opitional or non opitional argument? Why 

2. Create two new variables, one with interger value 77 and another one with the strnig 99. 

3. Use your variables to print `77%99%77` by changing the value of one of the optional arugments in `print`

In [28]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

1. sep is a string and opitional argument that is not necessary to run the print function. 

In [32]:
# 2. 
a = 77
print(type(a))

b = '99'
print(type(b))

<class 'int'>
<class 'str'>


In [46]:
# 3. 
print(a,b,a, sep='%') #print using `sep`

print(f"{a}%{b}%{a}") #print using a f"" print statement 

77%99%77
77%99%77
